# Generated by Django 3.2.5 on 2021-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('answer_status', models.BooleanField(default=False)),
                ('is_disagree', models.BooleanField(default=False)),
                ('answerer', models.ManyToManyField(related_name='answerer_for_playing', to='registration.Player')),
                ('requester', models.ManyToManyField(related_name='requester_for_playing', to='registration.Player')),
            ],
        ),
    ]
