# Generated by Django 3.2.5 on 2021-08-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_choices', models.CharField(max_length=255, verbose_name='Choices user1')),
                ('user2_choices', models.CharField(max_length=255, verbose_name='Choices user2')),
                ('winer_list', models.CharField(max_length=255, verbose_name='List of wins in round')),
                ('start_game_time', models.DateTimeField(auto_now_add=True, verbose_name='Time when game was start')),
                ('total_winer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_winer', to='registration.player')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='registration.player')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='registration.player')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayingRequest',
        ),
    ]
