# Generated by Django 3.2.5 on 2021-08-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210809_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameTable',
        ),
    ]
